#+TITLE: My Notes
#+OPTIONS: H:4
#+STARTUP: overview
#+STARTUP: align
#+TODO: TODO IN-PROGRESS WAITING DONE


* IN-PROGRESS read emacs basic

* Emacs
** Install & Configuration
Download for Windows https://ftp.gnu.org/pub/gnu/emacs/windows/
This version: emacs-24.5-bin-i686-mingw32.zip
Extract it to C:\emacs, so you will have C:\emacs\emacs-24.5-bin-i686-mingw32\
Make a shortcut of this file /bin/runemacs.exe and copy to your notes folder say C:\c\notes\
Then right click, select Properties of the shortcut and change the ~Start In~ to =C:\c\notes= 
Set a HOME user environment variable in Windows as ~C:\c\notes~
Include a file ~.emacs~ in ~C:\c\notes~ 
Your home folder in Emacs is ~C:\c\notes~
~/.emacs 
~(setq org-catch-invisible-edits 'smart)~

** Basics
#+NAME: tab:emacs-basics
| Help             |                                                      |
|------------------+------------------------------------------------------|
| C-h f            | Search by command, get shortcut                      |
| C-h v            | Get variable value                                   |
|                  |                                                      |
| File             |                                                      |
|------------------+------------------------------------------------------|
| C-x C-s          | Save                                                 |
| C-x C-c          | quit emacs                                           |
|                  |                                                      |
| Editing          |                                                      |
|------------------+------------------------------------------------------|
| _underlined_     |                                                      |
| ~verbatim~       |                                                      |
| =verbatim=       |                                                      |
| +strike_through+ |                                                      |
| /Italics/        |                                                      |
| C-c .            | Insert timestamp                                     |
|                  |                                                      |
| C-k              | Remove line, Delete Line                             |
| C-x u            | Undo                                                 |
| C-a              | Beginning of line                                    |
| C-e              | End of line                                          |
| C-h k            | Explain what key-combo will do                       |
| C-S-Bksp         | Kill whole line                                      |
| C-x u            | undo                                                 |
|                  |                                                      |
| <q               | =#+BEGIN_QUOTE=                                      |
| <H               | =#+BEGIN_HTML=                                       |
| <c               | =#+BEGIN_CENTER=                                     |
| <e               | =#+BEGIN_EXAMPLE=                                    |
| c-c ;            | =#+BEGIN_COMMENT=                                    |
|                  |                                                      |
|                  |                                                      |
| Table            |                                                      |
|------------------+------------------------------------------------------|
| C-c -            | Insert a horizontal line below                       |
| M-S-<down>       | Insert a new row above                               |
| C-c <RET>        | Insert horizontal line and a new row below           |
| M-S-<up>         | Delete a current row                                 |
|                  |                                                      |
| M-S-<right>      | Insert new column on the right                       |
| M-S-<left>       | Delete current column                                |
|                  |                                                      |
| C-c <SPC>        | Blank current field                                  |
|                  |                                                      |
| S-<TAB>          | Move to previous field                               |
| M-<up>/<down>    | Move a row                                           |
| M-<left>/<right> | Move a column                                        |
|                  |                                                      |
| C-c \vert{}      | After text is selected, convert to table             |
|                  |                                                      |
| Moving           |                                                      |
|------------------+------------------------------------------------------|
| C-l              | Scroll current line to center                        |
| C-x b            | switch to another buffer                             |
| M-<              | Move to beginning of buffer                          |
| M->              | Move to end of buffer                                |
| M-g M-g          | Go to a line                                         |
| C-c C-j          | org-goto. Search in headlines only                   |
|                  |                                                      |
| Windows          |                                                      |
|------------------+------------------------------------------------------|
| C-x 0            | remove current window                                |
| C-x 1            | make active window the only one, close help window   |
| C-x 2            | Split horizontally                                   |
| C-x 3            | split vertically                                     |
| C-x o            | move to other window                                 |
|                  |                                                      |
| Regions          | (selection)                                          |
|------------------+------------------------------------------------------|
| C-space          | mark beginning of region, then move cursor to select |
| C-x h            | Copy all in buffer                                   |
| C-g              | deactive mark                                        |
|                  |                                                      |
| Kill & Copy      |                                                      |
|------------------+------------------------------------------------------|
| C-w              | kill region (cut)                                    |
| M-w              | copy to kill-ring (shared with other buffers)        |
| C-y              | yank                                                 |
|                  |                                                      |
| Search           |                                                      |
|------------------+------------------------------------------------------|
| C-s, C-r         | search string, forward/backward                      |
| Return           | quit searching                                       |
| M-C-s            | forward regex search                                 |
| M-C-r            | backward regex search                                |
|                  |                                                      |

** Headline
Subtree recycling =TAB=
Global cycling *C-u TAB*
Show all, including drawers *C-u C-u C-u TAB*

*** Headline and List Navigation

| C-c C-n | Next heading                     |
| C-c C-p | Previous heading                 |
| C-c C-f | Next heading same level          |
| C-c C-b | Previous heading same level      |
| C-c C-u | Backward to higher level heading |
|---------+----------------------------------|

C-x n s :: Work on one section
C-x n w :: Back to outline

C-c C-j :: jump to different heading. C-g to exit. up/down to move headline, ~/~ sparse-tree search

M-<RET> or C-<RET> :: insert heading

M-S-<left>
M-S-<right> :: Decrease/increase indentation the item and its subitems

M-left
M-right :: Decrease/increase only the parent item

*** Drawer
C-c C-x d :: Create a drawer

:MYDRAWER: 
This is inside the drawer

:END:

** Symbol and Escape
=\vert{}= :: |
[[http://orgmode.org/worg/org-symbols.html][Table of Symbols]]

** =TODO=
Headline + =TODO=
S-left/right Cycle through *TODO*, *DONE* and empty.

** Sparse Tree, Search
C-c / r :: Search regex, C-c C-c to quit.
M-g M-n :: Next match
M-g M-p :: Previous match

** Link
[[http://orgmode.org/manual/Link-format.html#Link-format][Here's description of the link]]

| C-c C-l | add or modify link                             |
|         | Or cusor to the right of end and hit BACKSPACE |
|---------+------------------------------------------------|
| C-c &   | Go back to previous position                   |
| C-c C-c | Update radio targets                           |


=[[My Target]]= By defalt, it leads to a text search

[[Link]] "Link" matches an exact headline

Something is referred to later in the file <<internal target>>
[[internal target]] will go to the target

#+NAME: Table One
| a  | table      |
|----+------------|
| of | four cells |
|----+------------|

Go to a named section [[Table One]]

<<<Radio target>>>. Just simply repeat the text and it will go to original place: radio target.

* PHP
** Array
*** array_merge, array_merge_recursive
array_merge
- only merge on the first level
- If key is the same, value at later array will overwrite the first array's value.

array_merge_recursive
- If key is the same, values will be appended as array
- Very different from array_merge

* CSS
* Drupal
** Theme
#+BEGIN_EXAMPLE
function lili_theme( $existing, $type, $theme, $path ) {
  return array(
    'lili_flair' => array(
      'variables' => array(
        'text' => NULL,
      ),
    ),
  );
}

function theme_lili_flair( $variables ) {
  if ( ! empty( $variables['text'] ) ) {
    return '<span class="li-tag li-tag-pill li-tag-color">' . $variables['text'] . '</span>';
  } else {
    return '';
  }
}

echo theme('lili_flair',array('text'=>'hi'));
#+END_EXAMPLE



* Wordpress
** RSS
Default template /wp-includes/feed-rss2.php

#+BEGIN_EXAMPLE
$args = array(
  'post_type' => array('blog'), // e.g. any
  'tag' => 'editors-choice',
  'orderby' => 'date', // Default. e.g. title
  'order' => 'DESC', // Default. e.g. ASC
);
query_posts($args);
#+END_EXAMPLE



** Wordpress Theme
   [[https://themeforest.net/item/newspapaer/5489609][Newspaper]]
* HTML
** Email
| Element   | Note                                                        |
|-----------+-------------------------------------------------------------|
| table     | always assign align, width,border, cellpadding, cellspacing |
| tr        | <tr style="padding:0;margin:0;line-height:0;" height="15">  |
|           | <td>&nbsp;</td>                                             |
|           | </tr> // empty row with height                              |
|           |                                                             |
| td        | Wrap text in td                                             |
|           |                                                             |
| Attribute |                                                             |
|-----------+-------------------------------------------------------------|
| style     | use =display: none!important;=                              |
|           |                                                             |

#+BEGIN_EXAMPLE
<style>
.sectionContainer {
  background-color: #ffffff;
  padding-right:10px !important;
  padding-left:10px !important;
}
.sectionTable {
  background-color: #ffffff;
}
@media only screen and (max-width:640px) {
.sectionTable {
  max-width:640px !important;
  width:100% !important;
}
}
@media only screen and (max-width:480px) {
.sectionTable {
  max-width:480px !important;
  width:100% !important;
}
.sectionContent .s480-w0 {
  display:none !important;
}
} 
</style>

<table>
  <tr>
    <td class="sectionContainer">
      <table border="0" cellpadding="0" cellspacing="0" width="640" class="sectionTable">
        <tr style="padding:0;margin:0;line-height:0;" height="15"><td>&nbsp;</td></tr>
        <tr>
          <td align="center" valign="middle" style="background-color:#004663;color:#ffffff;margin:0;font-size:24px;font-family:Georgia;font-weight:normal;">
            Section #1  
          </td>
        </tr>
        <tr style="padding:0;margin:0;line-height:0;" height="10"><td>&nbsp;</td></tr>
        <tr>
          <td align="center" valign="top">
            
          </td>
        </tr>
      </table>
    <td>
  </tr>
</table>

#+END_EXAMPLE


* Linux
** System Version, Distro

| =uanme -a=           | all info     |
| =uname -r=           | Kernal       |
|                      |              |
| =cat /etc/*-release= | Linux distro |
| =cat /etc/issue=     |              |
| =cat /proc/version=  |              |
| =lsb_release -a=     | Ubuntu only  |
|                      |              |

** User Management & Superuser
=sudo adduser corey=
=sudo deluser corey=
List all users =cut -d: -f1 /etc/passwd` or `cat /etc/passwd=
- Login username
- Password (always x)
- UID (<500 are system accounts, > 500 are users)
- Group ID (GID)
- Comment field
- Location of HOME directory
- Default shell for the user

Switch to superuser 
- Debian =sudo su=
- RedHat =sudo -=

** System 
Resource Limits
=sudoedit /etc/security/limits.conf=

System Logs
| /var/log/syslog   | general system log                         |
| /var/log/auth.log | system auth logs                           |
| /var/log/mail.log | system mail logs                           |
| /var/log/messages | general log messages                       |
| /var/log/dmesg    | kernel ring buffer msg, e.g. system bootup |
|                   |                                            |

Search a word `warthog` in .gz files
=zgrep -i warthog /var/log/*.gz= 

** Filesystem
*** /dev /mnt /media
=/dev/sd*1= :: sd for SATA or SCSI drive, numeric 1 for partition, * for a, b, etc.
=/dev/hd*1= :: hd for IDE drive, * for a, b, etc.
=/media/win1=
 - virtual directory  where files are accessed file here. 
 - Equivalent to d:\. One or more partitions can be assigned to one media

=sudo mkdir /media/win2= :: create a virtual directory is easy
=sudo mkdir /mnt/my_mount= :: also creates a virtual directory

=sudo mount -t ext4 /dev/sda1 /mnt/my_mount= :: Mount a partitioned device to a virtual directory
=sudo gedit /etc/fstab=
, =/dev/hdb1 media/win1 vfat users,rw,owner,umask=000 0 0=
, then reload =sudo mount -a=
- Permanently mount during bootime

*** /etc system configuration files
*** Disk space
| =df -h=      | Disk usage on OS                  |
|              | h for human-readable.             |
| =du -sh=     | Current folder size               |
| =du -sh ./*= | Only 1st level child folders size |
|              |                                   |

** Processes
| =ps -ef=                   | List of running processes      |
| =sudo ls -l /proc/PID/exe= | file path for command, sub PID |
|                            |                                |

*** =top=
First line: current time, system up time, number of users logged in, load average (1, 5, 15 minutes; >2 is busy). 
Second line: total processes: running, sleeping, stopped and zombie (have finished but parent process hasn't responded)

Third line: CPU utilization: us (user), sy (system), ni (nice: time running niced user processes), wa (time waiting for I/O completion), hi (time spent servicing hardware interrupts), si (software interrupts), st (stolen from this vm by the hypervisor)

Memory usage
	- Line 1 reflects physical memory: total, used, free and buffers
	- Line 2 reflects virtual memory: total, used, free and cached 

Detailed for each process
| PID  | The process ID of the process             |
| USER | The user name of the owner of the process |
| PR   | The priority of the process               |
| NI   | The nice value of the process             |
	- NI: The nice value of the process
	- VIRT: The total amount of virtual memory used by the process
	- RES: The amount of physical memory the process is using
	- SHR: The amount of memory the process is sharing with other processes
	- S: The process status (D = interruptible sleep, R = running, S = sleeping, T = traced
	- or stopped, or Z = zombie)
	- %CPU: The share of CPU time that the process is using
	- %MEM: The share of available physical memory the process is using
	- TIME+: The total CPU time the process has used since starting
	- COMMAND: The command line name of the process (program started)


Type `f` for interaction: set sort, display more fields/columns

*** Memory
Total memory: =grep MemTotal /proc/meminfo=
Memory usage: =free -ltm -s 1=
Delay 1 second: =-s 1=
=-m=: in megabyte. e.g. -g
=-t=: show Total
=-l=: show Low and High

** Network
All active NIC and IP addresses: =ifconfig=
All enabled and disabled NIC: =ifconfig -a=
View one NIC (interface): =ifconfig eth0=

Ethernet interface: eth0, eth1
Wireless network interface: wlan0, wlan1
Loopback interface for system internal communication: =lo=

*** Port
If a port is in use =telnet localhost 9000=, if it's connected, it's in use.
List all ports in use: =netstat -lp= or =netstat -nlp= to list in numeric form.
Search a port =netstat -nlp | grep 8000=
Which file is using the port =lsof | grep 9000=
Wireless network adapters =iwconfig=

*** CIDR Netmask (Network Mask)
CIDR netmask
- 10.0.75.5/24 = 10.0.75.5 AND 255.255.255.0 = 10.0.75.0 
	(10.0.75.5 is in the 10.0.75.0 subnet)
- 10.0.75.5/32 = 10.0.75.5 AND 255.255.255.255 = 10.0.75.5 (a single host)
- 10.0.75.5/16 = 10.0.75.5 AND 255.255.0.0     = 10.0.0.0
- 10.0.75.5/8  = 10.0.75.5 AND 255.0.0.0       = 10.0.0.0

Private IPv4 address spaces
- 10.0.0.0 - 10.255.255.255 = 10.0.0.0/8 (16 million number of addresses)
- 172.16.0.0 - 172.31.255.255 = 172.16.0.0/12 (255.240.0.0) (1 million number of addresses)
- 192.168.0.0 - 192.168.255.255 = 192.168.0.0/16 (65,536 number of addresses)

** Hardware
PCI devices: =lspci=
USB devices: =lsusb=
Most of devices: =lshal=

** Package & Repository
=cat /etc/apt/sources.list=

Repositories
- Main
- Universe: maintained by Ubuntu community
- Backports: newest version of pkg
- Multiverse: not free pkg
- Restricted: hardware drivers etc.

*** Package Management
**** =dpkg= lowest level.
List installed packages: =dpkg -l= 
How to read dpkg output
- First 3 columns show Desired action, Package status and Error flags
- Desired action
  - unknown (u), install (i), hold (h), remove ( r ), purge (p)
- Package Status
  - Not-installed	`n`
  - Config-files	`c`
  - Half-installed	H
  - Unpacked	U
  - Half-configured	F
  - Triggers-awaiting	W
  - Triggers-pending	`t`
  - Installed	`i`
- Error flags
  - <empty> = (none), R = Reinst-required

If a package is installed: =dpkg -l wget=
Search if a package is installed: =dpkg -l | grep wget= or ~dpkg -l 'wget*'~

List files owned by a package =dpkg -L cron=

Find which package owns a file =dpkg -S /etc/crontab=

**** =apt-get= =apt-cache=
Search package by name or title and read installation status: =apt-cache search php=
- Before each package name, if you see `i` the package is installed
- `v` the package is virtual (installed)
- `c` the package is deleted but not configuration files
- `p`, no trace at all or `v`, it's not installed.
- There might be a second character which indicates the action to be performed on the package.

Find out dependencies: =apt-cache showpkg php5-xmlrpc=
- Other packages must be installed before php5-xmlrpc (under Dependencies)
- Other packages depend on php5-xmlrpc (under Reverse Depends)
- Different versions of this package you can install (under Provides)

**** =aptitude= Highest Level
It removes orphan packages automatically



** Commands
*** Run Sequentially
=lspci; lsusb=
If the first command not successful, 2nd command will not run: =lspci && lspci=

*** =man=
=man -k processes= Search `processes` in command names and description
=man -f ls= Search in command names and title

*** =cd -= Navigate to previous directory (back)
*** =wc=
| =-l= | Line Count      | =ps -ef \vert wc -l= |
| =-w= | Word Count      |                      |
| =-c= | Byte Count      |                      |
| =-m= | Character Count |                      |
|      |                 |                      |

*** Replace String  =sed= 
Replace all (g) Nick with John
=cat report.txt | sed 's/Nick/John/g' > report_new.txt=


** Interesting Commands
*** sudo
Install sudo =apt-get update && apt-get install -y sudo less=
Run sudo interactive =sudo -i=

*** byobu
Create multiple terminals and switch between.
=apt-get install byobu=

** Ubuntu Unity

| C-M t   | open Terminal          |
| M-<F2>  | run command/open app   |
| Super-T | Open Trash             |
| Super-F | Open Files             |
| Alt-`   | Switch between windows |
|         | of the current app     |
|         |                        |

** Ubuntu Personal Package Archive PPA
Add a LibreOffice package from PPA to Software Sources
=sudo add-apt-repository ppa:libreoffice/ppa=, then =sudo apt-get update=
Remove the package source
=sudo add-apt-repository --remove ppa:libreoffice/ppa=, =apt-get update=

Remove it and downgrade back to previous version before using PPA
=sudo apt-get install ppa-purge=, =sudo ppa-purge ppa:libreoffice/ppa=

* Pantheon
** Deploy
#+BEGIN_EXAMPLE
terminus site deploy --site=<s> --env=<e> --sync-content --cc
#+END_EXAMPLE


* Tools

** phpStorm
Help > Default Keymap Reference

*** HTML (CSS and Javascript)
Right click on element and select _Show Applied Sytles for Tag_

** Chrome
*** Flash Couldn't Load Plugin
Properites > Security, give Full Control for Everyone in this folder
C:\Users\you\AppData\Local\Google\Chrome\User Data\PepperFlash\some.version.number

** Windows 10
*** Meter an Ethernet Connection
Run regedit: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\DefaultMediaCost
Right click on the key > Permissions > Advanced > ~Change~ next to Owner on the top 
Type ~Administrators~ and Check Names
Check the box next to *Replace owner on subcontainers and objects* and click *OK*
Back in the *Permissions for DefaultMediaCost* window, click *Administrators* to select the group
Assign *Full Control Allow*, then *OK*
Right click /DefaultMediaCost > Ethernet/ and /Modify/
Change from 1 to 2 for metered (DWORD 32-bit, Base Hexadecimal)
 
